### ISSUE TITLE
关于bubbleSort3的一个疑问

### ISSUE THREAD

**Issue by gaoZhanGithub** [damonare/Sorts#3]
我这里执行demo发现 bubbleSort3 执行循环的次数是105 和没有优化的 bubbleSort的循环次数一样，是我理解有问题吗？
运行结果分别如下：
![image](https://user-images.githubusercontent.com/8189221/30103970-db82fbc6-9326-11e7-934b-b45273003628.png)
![image](https://user-images.githubusercontent.com/8189221/30103993-e6494114-9326-11e7-83e5-f14eb4b401ad.png)

**Comment by damonare** [comment]
耗时不一样，而且这个耗时也并不是稳定的

**Comment by liujunjia1996** [comment]
我也感觉 sort3 有问题，和优化前本质上都是一样的啊：每执行一次 for 循环，循环的长度减1。至于耗时的问题，我这边测试这三个 bubbleSort 的耗时与位置有关，第一个执行的总是最慢的。
